# This is a basic workflow to help you get started with Actions

name: AmazingHelloWorld
description: Yet Another Amazing Hello World Echo.

inputs:
  url:
    description: 'url'
    required: true
    default: ''
  username:
    description: 'username'
    required: true
    default: ''
  password:
    description: 'password'
    required: true
    default: ''


runs:
  using: 'docker'
  image: url
  credentials:
     username: username
     password: password
