# This is a basic workflow to help you get started with Actions

name: AmazingHelloWorld
description: Yet Another Amazing Hello World Echo.

# Steps represent a sequence of tasks that will be executed as part of the job
runs:
  # Runs a single command using the runners shell
  - name: Run a one-line script
    run: echo Hello, world!
