name: 'AmazingHelloWorld'
description: 'Greet someone 1 2 3 4 5 6 7 8 9 10!!'
inputs:
  base-path:
    description: 'Base path for postman files'
    required: true
    default: './'
  postman-collection-filename:
    description: 'Postman collection file name'
    required: true
    default: 'collection.postman_collection.json'
  postman-environment-filename:
    description: 'Postman environment file name'
    required: true
    default: 'environment.postman_environment.json'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
      
    - id: pull_crapi
      run: | 
        curl -o docker-compose.yml https://raw.githubusercontent.com/OWASP/crAPI/main/deploy/docker/docker-compose.yml
        docker-compose pull
        docker-compose -f docker-compose.yml --compatibility up -d
      shell: bash
      
    - id: random-number-generator
      run: echo "::set-output name=random-number::$(echo $RANDOM)"
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - id: pull_pynt
      shell: bash
      run: |
        docker pull ghcr.io/pynt-io/pynt:latest
        docker run -v "${{ inputs.base-path }}":/etc/pynt/ --rm --network="host"  ghcr.io/pynt-io/pynt:latest -c "${{ inputs.postman-collection-filename }}" -e "${{ inputs.postman-environment-filename }}"
