name: 'AmazingHelloWorld'
description: 'Greet someone 1 2 3 4 5 6 7 8 9 10!!'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-number::$(echo $RANDOM)"
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - id: pull-crapi
      shell: bash
      run: |
        docker pull ghcr.io/amiros17/stam:initial
        docker run ghcr.io/amiros17/stam:initial ${{ inputs.who-to-greet }}.
