name: 'AmazingHelloWorld'
description: 'Greet someone 1 2 3 4 5 6 7 8 9 10!!'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-number::$(echo $RANDOM)"
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - id: pull-crapi
      shell: bash
      run: | 
        curl -o docker-compose.yml https://raw.githubusercontent.com/OWASP/crAPI/main/deploy/docker/docker-compose.yml
        docker-compose pull
        docker-compose -f docker-compose.yml --compatibility up -d
    - id: pull-newman
      shell: bash
      run: docker pull postman/newman
    - id: pull-crapi-collections
      shell: bash
      run: |
        mkdir collections
        pushd collections
        wget https://raw.githubusercontent.com/OWASP/crAPI/main/postman_collections/Crapi.postman_environment.json
        wget https://raw.githubusercontent.com/OWASP/crAPI/develop/postman_collections/crAPI%20Accepted.postman_collection.json
        wget https://github.com/OWASP/crAPI/raw/main/postman_collections/car.mp4
        mkdir postman_collections
        mv car.mp4 postman_collections/
        popd
